name: Build Guacamole RADIUS Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build RADIUS Extension
        run: |
          cd extensions/guacamole-auth-radius
          mvn clean package

      - name: Upload built JAR
        uses: actions/upload-artifact@v2
        with:
          name: guacamole-auth-radius
          path: extensions/guacamole-auth-radius/target/*.jar
